dataset: M3FD_Detection
split: test
image_size: 256
batch_size: 8
data_root: /data2/hubin/datasets
device: cuda:5

etrl:
  checkpoint: runs/vis2ir_etrl_M3FD/version_2/checkpoints/last.ckpt

precompute:
  output_dir: /data1/hubin/AlignIR/precompute/ir0/M3FD
  split: test
  batch_size: 8
  use_split_subdir: true
